// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwaavcqhdxjlnhpzsekc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3YWF2Y3FoZHhqbG5ocHpzZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTk0NzksImV4cCI6MjA2OTE5NTQ3OX0.R9naaEMeX6CEv5UVNaTq3Xn83svXoowlTmfw5zCq9gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});